<a href="https://colab.research.google.com/github/Subroy1/MSAI_AllPracticeModules/blob/main/colab_activity13_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Colab Activity 13.4: Multiclass Logistic Regression

**Expected Time = 90 minutes**


This activity focuses on implementing `LogisticRegression` estimator using three approaches for multi class classification.  Two of these, one vs. rest and multinomial, are available using the estimator directly.  The third example, one vs. one, is implemented from the scikit-learn `multiclass` module.  Most important is that you can consider each of these models as options when building classification models and that you select the best depending on your identified metric.

#### Index

- [Problem 1](#Problem-1)
- [Problem 2](#Problem-2)
- [Problem 3](#Problem-3)
- [Problem 4](#Problem-4)
- [Problem 5](#Problem-5)
- [Problem 6](#Problem-6)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsOneClassifier
# OVR are Multinomial classification are available in the estimator itself.

In [20]:
penguins = sns.load_dataset('penguins').dropna()
y = penguins.species
X  = penguins.drop(columns= {'species','island','sex'})

Chinstrap Adelie Gentoo Gentoo

In [21]:
print(y[175], y[17],y[250],y[300])

Chinstrap Adelie Gentoo Gentoo

### The Data

Below, the `penguins` data is loaded and the target feature for all classes is converted to a numeric value.  Thus, we have three classes where 0, 1, and 2 represent Adelie, Chinstrap, and Gentoo respectively.

In [27]:
y_factorize=pd.factorize(y)
y_num = y_factorize[0]
categories = y_factorize[1]
print(categories)

Index(['Adelie', 'Chinstrap', 'Gentoo'], dtype='object')

In [ ]:
X.head()

   bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0            39.1           18.7              181.0       3750.0
1            39.5           17.4              186.0       3800.0
2            40.3           18.0              195.0       3250.0
4            36.7           19.3              193.0       3450.0
5            39.3           20.6              190.0       3650.0

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y ,random_state=518)

[Back to top](#-Index)

### Problem 1

#### One vs. Rest Classification


To begin, use the `LogisticRegression` estimator with the argument `multi_class = 'ovr'`, `max_iter=1000`, and `random_state = 42` to instantiate a model named `ovr_lgr`. The use itto fit the model on the training data.

In [29]:
ovr_lgr = LogisticRegression(multi_class='ovr', random_state=42, max_iter=1000 )
# Answer check
ovr_lgr

LogisticRegression(max_iter=1000, multi_class='ovr', random_state=42)

[Back to top](#-Index)

### Problem 2

#### Examining the Probabilities


Use the `predict_proba` function to examine the predicted probabilities on the testing data.  Assign these to `ovr_probs` as an array below.

In [32]:
import warnings
warnings.filterwarnings('ignore')

ovr_lgr.fit(X_train, y_train)
ovr_probs = ovr_lgr.predict_proba(X_test)
# Answer check
pd.DataFrame(ovr_probs, columns = ['p(adelie)', 'p(gentoo)', 'p(chinstrap)']).head()
# p(adelie)	p(gentoo)	p(chinstrap)
# 0	9.997758e-01	3.366719e-05	0.000191
# 1	2.112815e-04	2.247698e-04	0.999564
# 2	6.633864e-05	1.776670e-07	0.999933
# 3	2.564999e-07	7.146215e-04	0.999285
# 4	9.835565e-01	1.312682e-09	0.016444

      p(adelie)     p(gentoo)  p(chinstrap)
0  9.999683e-01  2.351634e-05      0.000008
1  2.123863e-04  6.596597e-05      0.999722
2  6.624596e-05  1.189690e-07      0.999934
3  2.560936e-07  8.895072e-04      0.999110
4  9.878666e-01  1.682196e-10      0.012133

[Back to top](#-Index)

### Problem 3

#### Trying multinomial


Now, instatiate a `LogisticRegression` estimator with `max_iter=10000`, `multi_class = 'multinomial'` and `random_state = 42`.  Fit the model on the training data as `multi_lgr` below.

In [33]:
multi_lgr = LogisticRegression(max_iter=10000, multi_class='multinomial', random_state=42).fit(X_train, y_train)

# Answer check
multi_lgr

LogisticRegression(max_iter=10000, multi_class='multinomial', random_state=42)

[Back to top](#-Index)

### Problem 4

#### Examining the Probabilities



Again, use the `predict_proba` function to examine the probabilities from the multinomial estimator above on the test data.  Assign them as an array to `multi_probs` below.

In [45]:
multi_probs = multi_lgr.predict_proba(X_test)

# Answer check
pd.DataFrame(multi_probs, columns = ['p(adelie)', 'p(gentoo)', 'p(chinstrap)']).head()
# 0	0.999990	3.395344e-06	0.000007
# 1	0.000409	4.414225e-04	0.999150
# 2	0.000030	4.059417e-07	0.999969
# 3	0.000002	4.213692e-04	0.999577
# 4	0.999912	3.187090e-10	0.000088
#penguins[136,276,285,273,133]
penguins.loc[285]

species              Gentoo
island               Biscoe
bill_length_mm         49.8
bill_depth_mm          16.8
flipper_length_mm     230.0
body_mass_g          5700.0
sex                    Male
Name: 285, dtype: object

[Back to top](#-Index)

### Problem 5

#### One vs. One Classifier


Similar in thinking to the one vs. rest approach, the one vs. one approach pairs every combination of the target class and builds a logistic model on this binary problem.  This means that for three classes you would have 6 different logistic regressors.  

The LogisticRegression estimator does not have this as a default. However, Scikit-learn implements this approach through the `OneVsOneClassifier` that accepts a classification estimator.

Below, instantiate a `OneVsOneClassifier` estimator with a `LogisticRegression`  estimator with parsmeter `max_iter=1000` and `random_state = 42`as `ovo_clf`. Fit this to the training data.

In [ ]:


ovo_clf = ''



# Answer check
ovo_clf

OneVsOneClassifier(estimator=LogisticRegression(max_iter=1000, random_state=42))

[Back to top](#-Index)

### Problem 6

#### Comparing Performance


Create a DataFrame that contains the scores on testing data in terms of accuracy.  Assign to `eval_df` below.  Which classifier performed best in terms of accuracy?  Assign your answer as a string -- `ovr`, `multi`, or `ovo` -- below to `best_acc`.

| estimator | accuracy |
| ------ | ------ |
| ovo | - |
| multi | - |
| ovo | - |

In [ ]:


best_acc = ''



# Answer check
print(best_acc)

ovr

Hopefully this activity increased your facility with the `LogisticRegression` estimator and how it can be used in a multi-class setting.  Of course, these options are things you may consider in a grid search rather than fitting each on their own, however the One vs. One will have to implemented as its own object.  Further, many of the fitting procedures should raise warnings.  As seen before, there is regularization behind the scenes so scaling the data should happen prior to fitting.  Further, you may need to give the estimator more time for the gradient descent to converge, which you can control with the `max_iter` argument.