<a href="https://colab.research.google.com/github/Subroy1/MSAI_AllPracticeModules/blob/main/Module%2010/colab_activity10_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Colab Activity 10.1: Working with Dates in `pandas`

**Estimated Time: 45 Minutes**


This activity focuses on working with datetime objects in pandas.  There is a good deal of functionality built into a DataFrame when working with datetime objects.  Specifically, you will examine how to convert dates to datetime objects using `pd.to_datetime`.  Also, you will examine how to use pandas to set the datetime as an index and use the dates to select specific data.


#### Index

- [Problem 1](#Problem-1)
- [Problem 2](#Problem-2)
- [Problem 3](#Problem-3)
- [Problem 4](#Problem-4)

In [2]:
import pandas as pd
import numpy as np

[Back to top](#-Index)

### Problem 1

#### Using `pd.to_datetime`


As you saw demonstrated, the `pd.to_datetime` function takes in a string representing a date and converts it to a datetime object.  This is a specific datatype in pandas.  Below, you are given a string `adate` representing a date and are to use the `to_datetime` method to convert the string to a datetime object.  Assign your solution as `adatetime` below.

In [13]:
import warnings
warnings.filterwarnings('ignore')

adate = '31-07-2000'
adatetime = ''

adatetime =pd.to_datetime(adate, dayfirst=True)

# Answer check
print(adatetime)
print(type(adatetime))
print(adatetime.day_of_year)

2000-07-31 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
213

[Back to top](#-Index)

### Problem 2

#### Dates in a `DataFrame`



Below, you are given a small DataFrame `sample_df` with two columns -- `date` and `price`.  The `date` feature is a string datatype.  You are to change the column to a datetime object.

Update the `date` column of the `data` DataFrame as datetime type.

In [94]:
data = {'price': [10.24, 11.34, 14.72, 13.90, 15.03],
       'date': ['11-01-2020', '11-02-2021', '11-03-2021', '11-04-2021', '11-05-2021']}

sample_df = pd.DataFrame(data)
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   price   5 non-null      float64
 1   date    5 non-null      object
dtypes: float64(1), object(1)
memory usage: 212.0+ bytes

In [50]:

sample_df['date']=pd.to_datetime(sample_df['date'])
# Answer check
print(sample_df['date'])
print(sample_df.dtypes)
sample_df

0   2020-11-01
1   2021-11-02
2   2021-11-03
3   2021-11-04
4   2021-11-05
Name: date, dtype: datetime64[ns]
price           float64
date     datetime64[ns]
dtype: object

   price       date
0  10.24 2020-11-01
1  11.34 2021-11-02
2  14.72 2021-11-03
3  13.90 2021-11-04
4  15.03 2021-11-05

[Back to top](#-Index)

### Problem 3

#### Extracting information from `datetime` objects



If a pandas series has a column of type `datetime`, you can extract information about the given date using the `.dt` function followed by the appropriate datetime method.  For example, in the above problem, we would be able to extract the month of each row with:

```python
sample_df['date'].dt.month
```

Below, a DataFrame containing oil prices in Bolivia is loaded.  You are to convert the `date` column to a datetime object and create a new column named `month` that contains the month of each price observation.

In [52]:
oil = pd.read_csv('data/oil.csv')
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [53]:

oil['date'] = pd.to_datetime(oil['date'])
oil['month']=oil['date'].dt.month
oil.info()
oil.head(2)

# Answer check
print('Counts of months in data\n==================')
print(oil['month'].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1175 non-null   float64
 2   month       1218 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(1)
memory usage: 23.9 KB
Counts of months in data
==================
month
1     111
5     111
7     111
3     110
8     110
4     107
6     107
2     101
12     90
10     89
9      87
11     84
Name: count, dtype: int64

[Back to top](#-Index)

### Problem 4

#### Slicing data with `datetime` index


One feature of using a `datetime` as an index is the ability to slice data using the dates.  For example, in the below data containing Microsoft stock data from the year 2020, once the date column is converted to `datetime` and is set as the index, we could slice all dates after March 1st with

```python
msft['2020-03-01':]
```

Using the `msft` data, change the `Date` column to `datetime` and set it to the index of the DataFrame.  Use the datetime index to select days between June 21st and September 22nd.  Assign the slice to the variable `msft_summer` below.

In [57]:
msft = pd.read_csv('data/msft.csv')
msft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       253 non-null    object
 1   High       253 non-null    float64
 2   Low        253 non-null    float64
 3   Open       253 non-null    float64
 4   Close      253 non-null    float64
 5   Volume     253 non-null    float64
 6   Adj Close  253 non-null    float64
dtypes: float64(6), object(1)
memory usage: 14.0+ KB

In [71]:
#write your solution here
msft['Date'] = pd.to_datetime(msft['Date'])
msft.set_index('Date', inplace=True)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-01-02,160.729996,158.330002,158.779999,160.619995,22622100.0,157.615112
2020-01-03,159.949997,158.059998,158.320007,158.619995,21116200.0,155.652542
2020-01-06,159.100006,156.509995,157.080002,159.029999,20813700.0,156.054855
2020-01-07,159.669998,157.320007,159.320007,157.580002,21634100.0,154.632004
2020-01-08,160.800003,157.949997,158.929993,160.089996,27746500.0,157.095032
...,...,...,...,...,...,...
2020-12-24,223.610001,221.199997,221.419998,222.750000,10550600.0,220.898361
2020-12-28,226.029999,223.020004,224.449997,224.960007,17933500.0,223.089996
2020-12-29,227.179993,223.580002,226.309998,224.149994,17403200.0,222.286728
2020-12-30,225.630005,221.470001,225.229996,221.679993,20272300.0,219.837250
2020-12-31,223.000000,219.679993,221.699997,222.419998,20942100.0,220.571106

In [99]:
msft.index.name
#Use the datetime index to select days between June 21st and September 22nd. Assign the slice to the variable msft_summer below.
msft_summer=msft['2020-06-21':'2020-09-22']

# Answer check
msft_summer.head()
msft_summer

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-06-22,200.759995,195.229996,195.789993,200.570007,32818900.0,197.904968
2020-06-23,203.949997,201.429993,202.089996,201.910004,30917400.0,199.227173
2020-06-24,203.250000,196.559998,201.600006,197.839996,36740600.0,195.211227
2020-06-25,200.610001,195.470001,197.800003,200.339996,27803900.0,197.678024
2020-06-26,199.889999,194.880005,199.729996,196.330002,54675800.0,193.721298
...,...,...,...,...,...,...
2020-09-16,210.649994,204.639999,210.619995,205.050003,26328100.0,202.814529
2020-09-17,204.330002,199.960007,200.050003,202.910004,34011300.0,200.697845
2020-09-18,203.649994,196.250000,202.800003,200.389999,55225300.0,198.205307
2020-09-21,202.710007,196.380005,197.190002,202.539993,39839700.0,200.331879
2020-09-22,208.100006,202.080002,205.059998,207.419998,33517100.0,205.158661