###  Colab Activity 19.1: Regression Models for Prediction

**Expected Time = 60 minutes**


This activity will use regression models to provide scores for unseen content (albums).  Using these scores, you can make recommendations for unheard albums to users. You are also given similar information as to that from the lecture in terms of *lofi* and *slick* scores for each artist.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)

In [2]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

#### Our Data

This example uses a synthetic dataset of reviews from five individuals and five albums.  The dataset is loaded and displayed below. Two additional columns `lofi` and `slick` are included to rate the nature of the music.

In [4]:
reviews = pd.read_csv('/content/sample_data/sample_reviews.csv', index_col=0)

In [5]:
reviews.head()

                 Alfred  Mandy  Lenny  Joan  Tino  slick  lofi
Michael Jackson     3.0    NaN    2.0   3.0   1.0      8     2
Clint Black         4.0    9.0    5.0   NaN   1.0      8     2
Dropdead            NaN    NaN    8.0   9.0   NaN      2     9
Anti-Cimex          4.0    3.0    9.0   4.0   9.0      2    10
Cardi B             4.0    8.0    NaN   9.0   5.0      9     3

[Back to top](#-Index)

### Problem 1

#### Considering Alfred

Define `X` to contain only the `slick` and `lofi` columns of the `reviews` dataframe, with rows where the `Alfred` column had missing values removed. Define `y`  as a new series y that contains the non-missing values from the `Alfred` column in the `reviews` dataframe.

Instantiate a new linear regression model and fit it to `X` and `y`. Assign this model to the variable `alfred_lr`.

Next, create a new dataframe `newx` that contains only the rows from the `reviews` dataframe where the `Alfred` column has missing (NaN) values. Additionally, ensure that you are selecting only the `slick` and `lofi` columns from these rows.

Finally, use the function `predict` on `alfred_lr` with argument equal to `newx` to calculate your predictions. Assign your result to `alfred_dd_predict`.

In [40]:
X= reviews.query('~Alfred.isna()')[["slick","lofi"]]
y = reviews[reviews['Alfred'].isna()==False]['Alfred'] #Define y as a new series y that contains the non-missing values from the Alfred column in the reviews dataframe.

alfred_lr = LinearRegression().fit(X,y)
newx=reviews.query('Alfred.isna()')[['slick','lofi']]

alfred_dd_predict = alfred_lr.predict(newx)


### ANSWER CHECK
print(X.join(y))
alfred_dd_predict

                 slick  lofi  Alfred
Michael Jackson      8     2     3.0
Clint Black          8     2     4.0
Anti-Cimex           2    10     4.0
Cardi B              9     3     4.0

array([3.75])

[Back to top](#-Index)

### Problem 2

#### User Vector for Alfred


Assign the coefficients of the linear regressions model `alfred_lr` to `alfred_vector` below.

In [ ]:

alfred_vector = ''


### ANSWER CHECK
pd.DataFrame(alfred_vector.reshape(1, 2), columns = ['slick', 'lofi'], index = ['Alfred'])

        slick  lofi
Alfred   0.25  0.25

[Back to top](#-Index)

### Problem 3

#### Considering Tino


Build a regression model `tino_lr` in a similar way as in Problem 1, but now for the user `Tino`.  Assign the prediction to `tino_dd_predict` as a numpy array below.

In [ ]:

tino_dd_predict = ''



### ANSWER CHECK
tino_dd_predict

array([6.71428571])

[Back to top](#-Index)

### Problem 4

#### Tino's user vector


Assign the coefficients of the linear regressions model `tino_lr` to `tino_vector` below.

In [ ]:

tino_vector = ''


### ANSWER CHECK
pd.DataFrame(tino_vector.reshape(1, 2), columns = ['slick', 'lofi'], index = ['Tino'])

         slick      lofi
Tino  1.714286  2.285714

[Back to top](#-Index)

### Problem 5

#### Completing the Table


Write a `for` loop to iterate over each column of `reviews` and perform the prediction process using the same columns of `slick` and `lofi` as inputs.

Create a DataFrame called `reviews_df_full` and complete the scores for each individual.

In [ ]:

reviews_df_full = ''



### ANSWER CHECK
reviews_df_full

                 Alfred  Mandy     Lenny      Joan      Tino  slick  lofi
Michael Jackson    3.00   9.00  2.000000  3.000000  1.000000      8     2
Clint Black        4.00   9.00  5.000000  4.664444  1.000000      8     2
Dropdead           3.75   3.85  8.000000  9.000000  6.714286      2     9
Anti-Cimex         4.00   3.00  9.000000  4.000000  9.000000      2    10
Cardi B            4.00   8.00  4.916667  9.000000  5.000000      9     3