<a href="https://colab.research.google.com/github/Subroy1/MSAI_AllPracticeModules/blob/main/Module%2015/MultiDimensional_Gradient_Descent_Tips_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
#tips dataset
tips=sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Imrove the moddel so that we want to predict the tip from the total_bill plus a constant offset .
tip = theta0 + theta1*bill

In [ ]:
model = LinearRegression(fit_intercept=True)
X=tips[["total_bill"]]
y=tips["tip"]
model.fit(X,y)

LinearRegression()

In [ ]:
model.intercept_, model.coef_

(np.float64(0.9202696135546731), array([0.10502452]))

This exercise is to compute the coef and intercept from scratch without using library.

In [ ]:
tips_with_bias= tips.copy()
tips_with_bias["bias"]= 1
X=tips_with_bias[["bias","total_bill"]]
X.head()

   bias  total_bill
0     1       16.99
1     1       10.34
2     1       21.01
3     1       23.68
4     1       24.59

In [ ]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
model.coef_

array([0.92026961, 0.10502452])

In [ ]:
y_preds  = X@np.array([model.coef_[0],model.coef_[1]])
y_preds

0      2.704636
1      2.006223
2      3.126835
3      3.407250
4      3.502822
         ...
239    3.969131
240    3.774836
241    3.301175
242    2.791807
243    2.892630
Length: 244, dtype: float64

In [ ]:
def mse_loss (theta, X,y):
    y_hat=theta[0]*X.iloc[:,0] + theta[1]*X.iloc[:,1]
    return np.mean((y_hat-y)**2)

In [ ]:
mse_loss(np.array([model.coef_[0],model.coef_[1]]), X,y)

np.float64(1.036019442011377)

In [ ]:
def mse_loss_single_arg(theta):
    return mse_loss(theta, X,y)

In [ ]:
mse_loss_single_arg(np.array([model.coef_[0],model.coef_[1]]))

np.float64(1.036019442011377)

In [ ]:
mse_loss_single_arg(([1.5,0.0])