### Required Assignment 20.1: Basic Aggregating of Models

This activity focuses on combining models in an ensemble to make predictions.  You will first create an ensemble on your own and then be introduced to the `VotingClassifier` from `scikit-learn` to implement these ensembles.  You will consider a classification problem and use Logistic Regression, KNN, and Support Vector Machines to build your ensemble.  

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)
- [Problem 6](#-Problem-6)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
from scipy.stats import mode
from sklearn.metrics import accuracy_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### The Data


The data was retrieved from [kaggle](https://www.kaggle.com/) and contains information from fetal Cardiotocogram exams that were classified into three categories:


- Normal
- Suspect
- Pathological

In [22]:
df = pd.read_csv('/content/sample_data/fetal.csv')

In [23]:
df.head()

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.0,0.000,0.000,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.0,0.006,0.003,0.0,0.0,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.0,0.008,0.000,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability                    2126 non-null   float64
 9   percentage_of_time_with_abnormal_long_term_variability  2126 non-null   float64
 10  mean_value_of_long_term_variability                     2126 non-null   float64
 11  histogram_width                                         2126 non-null   float64
 12  histogram_min                                           2126 non-null   float64
 13  histogram_max                                           2126 non-null   float64
 14  histogram_number_of_peaks                               2126 non-null   float64
 15  histogram_number_of_zeroes                              2126 non-null   float64
 16  histogram_mode                                          2126 non-null   float64
 17  histogram_mean                                          2126 non-null   float64
 18  histogram_median                                        2126 non-null   float64
 19  histogram_variance                                      2126 non-null   float64
 20  histogram_tendency                                      2126 non-null   float64
 21  fetal_health                                            2126 non-null   float64
dtypes: float64(22)
memory usage: 365.5 KB

In [25]:
df['fetal_health'].value_counts()

fetal_health
1.0    1655
2.0     295
3.0     176
Name: count, dtype: int64

In [26]:
X = df.drop('fetal_health', axis = 1)
y = df['fetal_health']

In [53]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

[Back to top](#-Index)

### Problem 1

#### Model Predictions

**10 Points**

Given the models below and the starter code, scale that data and train the models on the data, assigning the predictions as an array to the given dictionary.

In [28]:
models = [LogisticRegression(), KNeighborsClassifier(), SVC()]
models[1]

KNeighborsClassifier()

In [29]:
results = {'logistic': [],
          'knn': [],
          'svc': []}
results

{'logistic': [], 'knn': [], 'svc': []}

In [30]:
### GRADED
i = 0
for model in models:
    #fit the model
    model.fit(X, y)
    #make predictions
    pred= model.predict(X)
    #add predictions to dictionary
    if(i==0):
        results['logistic'] = pred
    elif(i==1):
        results['knn'] = pred
    else:
      results['svc'] = pred

    #track predictions with predictions -- should have three
    i += 1

# YOUR CODE HERE


### ANSWER CHECK
results

{'logistic': array([2., 1., 1., ..., 2., 2., 1.]),
 'knn': array([2., 1., 1., ..., 2., 2., 1.]),
 'svc': array([2., 1., 1., ..., 2., 2., 1.])}

[Back to top](#-Index)

### Problem 2

#### Majority Vote

**10 Points**

Using your dictionary of predictions, create a DataFrame called `prediction_df` and add a column to the DataFrame named `ensemble_prediction` based on the majority vote of your predictions.

In [81]:
### GRADED
results_models_df=pd.DataFrame(results)
results_models_df['ensemble_prediction'] = mode(results_models_df, axis=1)[0]
results_models_df.head()
prediction_df = pd.DataFrame()
prediction_df['ensemble_prediction'] = ''

#results_models_df[results_df['knn']!=results_df['svc']].head()

# YOUR CODE HERE
prediction_df['ensemble_prediction'] = results_models_df['ensemble_prediction']
prediction_df=results_models_df

### ANSWER CHECK
prediction_df.head()

   logistic  knn  svc  ensemble_prediction
0       2.0  2.0  2.0                  2.0
1       1.0  1.0  1.0                  1.0
2       1.0  1.0  1.0                  1.0
3       1.0  1.0  1.0                  1.0
4       1.0  1.0  1.0                  1.0

[Back to top](#-Index)

### Problem 3


#### Accuracy of Classifiers

**10 Points**


Create a list of accuracy scores for each of the classifiers.  Use this list with the columns to create a DataFrame named `results_df` to hold the accuracy scores of the classifiers.  What rank was your ensemble?

In [83]:
### GRADED
accuracies = []
results_df = pd.DataFrame(columns = ["logistic","knn","svc","ensemble_prediction"])
for col in prediction_df.columns:
    # put your answer here
    print(col)

# YOUR CODE HERE
lr_acc=accuracy_score(y,results_models_df["logistic"])
accuracies.append(lr_acc)
results_df.loc[0,"logistic"]=lr_acc

knn_acc=accuracy_score(y,results_models_df["knn"])
accuracies.append(knn_acc)
results_df.loc[0,"knn"]=knn_acc

svc_acc=accuracy_score(y,results_models_df["svc"])
accuracies.append(svc_acc)
results_df.loc[0,"svc"]=svc_acc

ensemble_acc= accuracy_score(y,prediction_df["ensemble_prediction"])
accuracies.append(ensemble_acc)
results_df.loc[0,"ensemble_prediction"]=ensemble_acc

### ANSWER CHECK
print(accuracies)
print(results_df)
accuracies

logistic
knn
svc
ensemble_prediction
[0.9045155221072436, 0.9374412041392286, 0.929444967074318, 0.9270931326434619]
   logistic       knn       svc ensemble_prediction
0  0.904516  0.937441  0.929445            0.927093

[0.9045155221072436, 0.9374412041392286, 0.929444967074318, 0.9270931326434619]

[Back to top](#-Index)

### Problem 4

#### Using the Voting Classifier

**10 Points**

Use the documentation and User Guide [here](https://scikit-learn.org/stable/modules/ensemble.html#voting-classifier) to create a voting ensemble using the `VotingClassifier` based on the majority vote using the same three classifiers `svc`, `lgr`, and `knn`.  Assign the accuracy of the ensemble to `vote_accuracy` below.

In [113]:
### GRADED
voter = ''
vote_accuracy = ''
# YOUR CODE HERE
voter = VotingClassifier(estimators=[('lr', models[0]), ('knn', models[1]), ('svc', models[2])],voting='hard') # this itself becomes a classifer and can be trained and used for predictions just like a normal classifier.
voter.fit(X,y)
y_preds=voter.predict(X)
vote_accuracy = accuracy_score( y,y_preds)

### ANSWER CHECK
vote_accuracy

0.9270931326434619

[Back to top](#-Index)

### Problem 5

#### Voting based on probabilities

**10 Points**

Consult the user guide and create a new ensemble that makes predictions based on the probabilities of the estimators.  **HINT**: This has to do with the `voting` parameter.  Assign the ensemble as `soft_voter` and the accuracy as `soft_accuracy`.

In [118]:
### GRADED
soft_voter = ''
soft_accuracy = ''
# YOUR CODE HERE
soft_voter = VotingClassifier(estimators=[('lr', models[0]), ('knn', models[1]), ('svc', SVC(probability=True))],voting='soft')
soft_voter.fit(X,y)
soft_voter_preds= eclf.predict(X)
soft_accuracy=accuracy_score (y,soft_voter_preds)

### ANSWER CHECK
soft_accuracy

0.9379115710253998

[Back to top](#-Index)

### Problem 6

#### Using different weights

**10 Points**

Finally, consider weighing the classifiers differently.  Use the Logistic Regression estimator as .5 of the weight in predicting based on majority votes, and the SVC and KNN as 0.25 each.  Assign the accuracy of these predictions on the test data to `weighted_acc`.

In [119]:
### GRADED
weighted_voter = ''
weighted_score = ''
# YOUR CODE HERE
weighted_voter = VotingClassifier (estimators = [('lr', models[0]), ('knn', models[1]), ('svc', SVC(probability=True))], voting = 'hard', weights=[0.5,0.25,0.25])
weighted_voter.fit(X,y)

weighted_score= accuracy_score(y,weighted_voter.predict(X))# order matters for weighted classifiers.

### ANSWER CHECK
weighted_score

0.9214487300094073